import { createServer, Factory , Model } from "miragejs";

export function makeserver(){
    createServer({
        models:{
            news:Model,
        },
        factories:{
            news: Factory.extend({
                id(i){
                    return i + 1;
                },
                title(i){
                    const titles =[
                        'Breaking: New Tech Launched',
                        'Health Update: New Diet Trends',
                        'Sports: Championship Results',
                        'Entertainment: Top Movie Releases',
                        'Business: Stock Market Surge',
                        'Tech: AI Advancements in 2024',
                        'Health: New Superfoods in 2024',
                        'Sports: Local Team Wins Championship',
                        'Entertainment: New Netflix Series Released',
                        'Business: Startups to Watch in 2024',
                        'Tech: The Future of Quantum Computing',
                        'Health: Exercise Trends for 2024',
                        'Sports: Upcoming Olympic Games',
                        'Entertainment: The Best Music Albums This Year',
                        'Business: Economic Forecast for 2024'
                    ]
                    return titles[i % titles.length]
                },
                content(i){
                    const content = [
                        'A revolutionary new technology has just been launched, and it’s set to change the landscape of various industries. This cutting-edge innovation combines advanced AI, quantum computing, and enhanced processing power, offering unparalleled speed and efficiency. From healthcare to finance, this new tech can handle tasks previously considered impossible or too complex. For example, it can analyze massive datasets for medical research, optimize business operations, or even power futuristic smart homes. Early adopters have already started reaping the benefits, especially in fields like logistics, cybersecurity, and education, where accuracy and speed are critical. The tech is also environmentally friendly, consuming less energy than previous models, which aligns with the global push toward sustainability. Experts predict that this innovation will lead to even greater advancements over the coming years, fundamentally transforming industries and making daily tasks more streamlined and efficient.',
                        'The health industry is buzzing with the latest diet trends, which are quickly gaining popularity. These new approaches to nutrition focus on balance, holistic well-being, and sustainability. Among the most talked-about trends is the rise of plant-based diets, which emphasize whole foods and reduced consumption of processed items. Not only do these diets promote weight management, but they also have a lower environmental impact, making them a popular choice for eco-conscious individuals. Another trend is intermittent fasting, where people limit their eating to specific windows during the day, which has been linked to improved metabolism and weight loss. Keto and low-carb diets continue to be favored by those looking to lose weight quickly while maintaining energy levels. Many health experts believe that personalization is the key, with diets tailored to individual needs, body types, and goals. These trends are reshaping how we approach healthy eating',
                        'In an unexpected twist, the results of the recent championship have left fans worldwide in disbelief. The highly anticipated event featured top teams battling for the coveted title, but the outcome was far from what anyone had predicted. The underdog team, widely regarded as the least likely to win, pulled off a series of stunning victories, ultimately clinching the championship title. Experts and analysts had favored more established teams, but the resilience, strategy, and teamwork of the surprise victors proved to be unstoppable. Fans of the defeated teams were left in shock, while supporters of the winning side celebrated their team’s unexpected rise to glory. This outcome is sure to be remembered for years to come, as it serves as a reminder that in sports, anything can happen. The championship results have sparked endless discussions and debates, with many eagerly anticipating the next season to see how teams will respond.',
                        'This season is packed with exciting new movie releases that are sure to captivate audiences across genres. Whether youre a fan of action-packed blockbusters, heartwarming dramas, or spine-chilling thrillers, theres something for everyone. One of the standout releases is a sci-fi epic that explores the future of artificial intelligence and human survival. The films stunning visual effects and gripping storyline have already earned it critical acclaim. For those who prefer something lighter, a romantic comedy about two unlikely lovers navigating modern relationships is gaining buzz for its relatable humor and charming cast. Meanwhile, horror enthusiasts wont want to miss the latest entry in a popular franchise that promises to deliver even more suspense and jump scares. The animation world is also buzzing with a beautifully crafted film that explores friendship, adventure, and self-discovery. This season’s movie lineup offers a fantastic array of cinematic experiences for all',
                        'The stock market experienced a significant surge today, with major indexes reaching new highs. The rally was fueled by a combination of positive economic data, investor optimism, and strong corporate earnings reports. Many companies in the tech, healthcare, and renewable energy sectors posted impressive quarterly results, boosting confidence in their future growth potential. Additionally, news of reduced inflationary pressures and improvements in consumer spending contributed to the overall market momentum. Analysts believe that this surge reflects a broader recovery in the global economy, following periods of uncertainty and market volatility. While some investors remain cautious about potential risks, such as geopolitical tensions or sudden policy changes, the current sentiment is overwhelmingly positive. The surge has led to increased interest in stock investments, with many seeing this as an opportune moment to capitalize on the upward trend. It remains to be seen how long the rally will last, but today’s performance has left investors excited.',
                        'Artificial intelligence (AI) has made remarkable strides in 2024, with innovations transforming industries at an unprecedented rate. AI is now playing a crucial role in areas such as healthcare, where it aids in diagnosing diseases, developing personalized treatment plans, and predicting patient outcomes. In business, AI is optimizing supply chains, improving customer service through chatbots, and streamlining operations by automating routine tasks. The rise of generative AI tools has also revolutionized content creation, enabling artists, writers, and designers to create new works with the help of algorithms. In education, AI is being used to develop adaptive learning systems that tailor content to individual student needs. Experts believe that AI will continue to evolve, with ethical considerations and regulations playing an important role in shaping its future. As these advancements unfold, they are expected to redefine how we live and work, pushing the boundaries of what was once thought possible.',
                        'The stock market experienced a significant surge today, with major indexes reaching new highs. The rally was fueled by a combination of positive economic data, investor optimism, and strong corporate earnings reports. Many companies in the tech, healthcare, and renewable energy sectors posted impressive quarterly results, boosting confidence in their future growth potential. Additionally, news of reduced inflationary pressures and improvements in consumer spending contributed to the overall market momentum. Analysts believe that this surge reflects a broader recovery in the global economy, following periods of uncertainty and market volatility. While some investors remain cautious about potential risks, such as geopolitical tensions or sudden policy changes, the current sentiment is overwhelmingly positive. The surge has led to increased interest in stock investments, with many seeing this as an opportune moment to capitalize on the upward trend. It remains to be seen how long the rally will last, but today’s performance has left investors excited.',
                        'The stock market experienced a significant surge today, with major indexes reaching new highs. The rally was fueled by a combination of positive economic data, investor optimism, and strong corporate earnings reports. Many companies in the tech, healthcare, and renewable energy sectors posted impressive quarterly results, boosting confidence in their future growth potential. Additionally, news of reduced inflationary pressures and improvements in consumer spending contributed to the overall market momentum. Analysts believe that this surge reflects a broader recovery in the global economy, following periods of uncertainty and market volatility. While some investors remain cautious about potential risks, such as geopolitical tensions or sudden policy changes, the current sentiment is overwhelmingly positive. The surge has led to increased interest in stock investments, with many seeing this as an opportune moment to capitalize on the upward trend. It remains to be seen how long the rally will last, but today’s performance has left investors excited.',
                        'This season is packed with exciting new movie releases that are sure to captivate audiences across genres. Whether youre a fan of action-packed blockbusters, heartwarming dramas, or spine-chilling thrillers, theres something for everyone. One of the standout releases is a sci-fi epic that explores the future of artificial intelligence and human survival. The films stunning visual effects and gripping storyline have already earned it critical acclaim. For those who prefer something lighter, a romantic comedy about two unlikely lovers navigating modern relationships is gaining buzz for its relatable humor and charming cast. Meanwhile, horror enthusiasts wont want to miss the latest entry in a popular franchise that promises to deliver even more suspense and jump scares. The animation world is also buzzing with a beautifully crafted film that explores friendship, adventure, and self-discovery. This season’s movie lineup offers a fantastic array of cinematic experiences for all',
                        'Artificial intelligence (AI) has made remarkable strides in 2024, with innovations transforming industries at an unprecedented rate. AI is now playing a crucial role in areas such as healthcare, where it aids in diagnosing diseases, developing personalized treatment plans, and predicting patient outcomes. In business, AI is optimizing supply chains, improving customer service through chatbots, and streamlining operations by automating routine tasks. The rise of generative AI tools has also revolutionized content creation, enabling artists, writers, and designers to create new works with the help of algorithms. In education, AI is being used to develop adaptive learning systems that tailor content to individual student needs. Experts believe that AI will continue to evolve, with ethical considerations and regulations playing an important role in shaping its future. As these advancements unfold, they are expected to redefine how we live and work, pushing the boundaries of what was once thought possible.',
                        'The health industry is buzzing with the latest diet trends, which are quickly gaining popularity. These new approaches to nutrition focus on balance, holistic well-being, and sustainability. Among the most talked-about trends is the rise of plant-based diets, which emphasize whole foods and reduced consumption of processed items. Not only do these diets promote weight management, but they also have a lower environmental impact, making them a popular choice for eco-conscious individuals. Another trend is intermittent fasting, where people limit their eating to specific windows during the day, which has been linked to improved metabolism and weight loss. Keto and low-carb diets continue to be favored by those looking to lose weight quickly while maintaining energy levels. Many health experts believe that personalization is the key, with diets tailored to individual needs, body types, and goals. These trends are reshaping how we approach healthy eating',
                        'This season is packed with exciting new movie releases that are sure to captivate audiences across genres. Whether youre a fan of action-packed blockbusters, heartwarming dramas, or spine-chilling thrillers, theres something for everyone. One of the standout releases is a sci-fi epic that explores the future of artificial intelligence and human survival. The films stunning visual effects and gripping storyline have already earned it critical acclaim. For those who prefer something lighter, a romantic comedy about two unlikely lovers navigating modern relationships is gaining buzz for its relatable humor and charming cast. Meanwhile, horror enthusiasts wont want to miss the latest entry in a popular franchise that promises to deliver even more suspense and jump scares. The animation world is also buzzing with a beautifully crafted film that explores friendship, adventure, and self-discovery. This season’s movie lineup offers a fantastic array of cinematic experiences for all',
                        'Artificial intelligence (AI) has made remarkable strides in 2024, with innovations transforming industries at an unprecedented rate. AI is now playing a crucial role in areas such as healthcare, where it aids in diagnosing diseases, developing personalized treatment plans, and predicting patient outcomes. In business, AI is optimizing supply chains, improving customer service through chatbots, and streamlining operations by automating routine tasks. The rise of generative AI tools has also revolutionized content creation, enabling artists, writers, and designers to create new works with the help of algorithms. In education, AI is being used to develop adaptive learning systems that tailor content to individual student needs. Experts believe that AI will continue to evolve, with ethical considerations and regulations playing an important role in shaping its future. As these advancements unfold, they are expected to redefine how we live and work, pushing the boundaries of what was once thought possible.',
                        'In an unexpected twist, the results of the recent championship have left fans worldwide in disbelief. The highly anticipated event featured top teams battling for the coveted title, but the outcome was far from what anyone had predicted. The underdog team, widely regarded as the least likely to win, pulled off a series of stunning victories, ultimately clinching the championship title. Experts and analysts had favored more established teams, but the resilience, strategy, and teamwork of the surprise victors proved to be unstoppable. Fans of the defeated teams were left in shock, while supporters of the winning side celebrated their team’s unexpected rise to glory. This outcome is sure to be remembered for years to come, as it serves as a reminder that in sports, anything can happen. The championship results have sparked endless discussions and debates, with many eagerly anticipating the next season to see how teams will respond.',
                        'The health industry is buzzing with the latest diet trends, which are quickly gaining popularity. These new approaches to nutrition focus on balance, holistic well-being, and sustainability. Among the most talked-about trends is the rise of plant-based diets, which emphasize whole foods and reduced consumption of processed items. Not only do these diets promote weight management, but they also have a lower environmental impact, making them a popular choice for eco-conscious individuals. Another trend is intermittent fasting, where people limit their eating to specific windows during the day, which has been linked to improved metabolism and weight loss. Keto and low-carb diets continue to be favored by those looking to lose weight quickly while maintaining energy levels. Many health experts believe that personalization is the key, with diets tailored to individual needs, body types, and goals. These trends are reshaping how we approach healthy eating',
                    ]
                    return content[i % content.length]
                },
                image(i){
                    const images = [
                        'https://media.istockphoto.com/id/2163036780/photo/female-nurse-analyzing-x-ray-at-desk-in-hospital.jpg?s=1024x1024&w=is&k=20&c=N1O6_DqqMT59_L_4RoIwSOMk2DNAlQ1o2tDiao0ebHI=',
                        'https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dGVjaHxlbnwwfHwwfHx8MA%3D%3D',
                        'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8dGVjaHxlbnwwfHwwfHx8MA%3D%3D',
                        'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRlY2h8ZW58MHx8MHx8fDA%3D',
                        'https://plus.unsplash.com/premium_photo-1663852296872-51c74244d487?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZGlldHxlbnwwfHwwfHx8MA%3D%3D',
                    ]
                    return images[i % images.length];
                },
                category(i){
                    const categories = ['Tech', 'Health', 'Sports', 'Entertainment', 'Business'];
                    return categories[i % categories.length];
                },
            }),
        },
        seeds(server){
            server.createList('news' , 100)
        },

        routes() {
            this.namespace = 'api';
      
            this.get('/news', (schema, request) => {
              let page = request.queryParams.page || 1;
              let pageSize = 10;
              let news = schema.news.all().models;
      
              let paginatedNews = news.slice((page - 1) * pageSize, page * pageSize);
      
              return { news: paginatedNews };
            });

      this.get("/categories", () => ({
        categories: ["All", "Tech", "Health", "Sports", "Entertainment", "Business"],
      }));
        }

    })
}